### ISSUE TITLE
Update Jackett to the latest version

### ISSUE THREAD

**Issue by marciogranzotto** [haberda/jackett-addon#10]
![image](https://user-images.githubusercontent.com/11080704/137605461-8f75f1d4-09cb-43cd-92ae-c84ebc1a414c.png)

**Comment by thumDer** [comment]
I would like to ask for this too. Also there is a supervisor warning that could be handled as well
`21-10-21 21:02:57 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of Jackett`
