### ISSUE TITLE
OpenVPN Routing Issue

### ISSUE THREAD

**Issue by dankfred** [haberda/jackett-addon#109]
Hello, I noticed that it's not routing any traffing through the vpn:

`/usr/sbin/openvpn --config /etc/openvpn/config.ovpn --script-security 2 --up /etc/openvpn/up-jackett.sh`

The `--up` script seems to stop openvpn from automatically configuring routes, a quick `ip route` shows that the "localNet" routes exist, but all openvpn routes never get set:

    2024-02-05 10:55:32 TUN/TAP device tun0 opened
    2024-02-05 10:55:32 net_iface_mtu_set: mtu 1500 for tun0
    2024-02-05 10:55:32 net_iface_up: set tun0 up
    2024-02-05 10:55:32 net_addr_v4_add: X.X.X.X/16 dev tun0
    // missing net_addr_v4_add lines here!
    2024-02-05 10:55:32 /etc/openvpn/up-jackett.sh tun0 1500 0 X.X.X.X 255.255.0.0 init

A quick test running `openvpn --config /etc/openvpn/config.ovpn --script-security 2` shows more routes added.
I'm not too familiar with openvpn, but from the [docs](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/):

> If --ifconfig is also specified, OpenVPN will pass the ifconfig local and remote endpoints on the command line to the --up script so that they can be used to configure routes such as:

Thank you

**Comment by haberda** [comment]
Yeah, this is an issue. Used to work, I'll try and figure it out.
